INSERT INTO countries (name, alfasitwo, alfasitothree, isocode) 
VALUES ('Afganistán', 'AF', 'AFG', '4'),
('Albania', 'AL', 'ALB', '8'),
('Alemania', 'DE', 'DEU', '276'),
('Andorra', 'AD', 'AND', '20'),
('Angola', 'AO', 'AGO', '24'),
('Anguilla', 'AI', 'AIA', '660'),
('Antártida', 'AQ', 'ATA', '10'),
('Antigua y Barbuda', 'AG', 'ATG', '28'),
('Arabia Saudí', 'SA', 'SAU', '682'),
('Argelia', 'DZ', 'DZA', '12'),
('Argentina', 'AR', 'ARG', '32'),
('Armenia', 'AM', 'ARM', '51'),
('Aruba', 'AW', 'ABW', '533'),
('Australia', 'AU', 'AUS', '36'),
('Austria', 'AT', 'AUT', '40'),
('Azerbaiyán', 'AZ', 'AZE', '31'),
('Bahamas', 'BS', 'BHS', '44'),
('Bangladés', 'BD', 'BGD', '50'),
('Barbados', 'BB', 'BRB', '52'),
('Baréin', 'BH', 'BHR', '48'),
('Belgica', 'BE', 'BEL', '56'),
('Belice', 'BZ', 'BLZ', '84'),
('Benin', 'BJ', 'BEN', '204'),
('Bermudas', 'BM', 'BMU', '60'),
('Bielorussia', 'BY', 'BLR', '112'),
('Birmania', 'MM', 'MMR', '104'),
('Bolivia', 'BO', 'BOL', '68'),
('Bosnia y Herzegovina', 'BA', 'BIH', '70'),
('Botsuana', 'BW', 'BWA', '72'),
('Brasil', 'BR', 'BRA', '76'),
('Brunéi', 'BN', 'BRN', '96'),
('Bulgaria', 'BG', 'BGR', '100'),
('Burkina Faso', 'BF', 'BFA', '854'),
('Burundi', 'BI', 'BDI', '108'),
('Bután', 'BT', 'BTN', '64'),
('Cabo Verde', 'CV', 'CPV', '132'),
('Camboya', 'KH', 'KHM', '116'),
('Camerún', 'CM', 'CMR', '120'),
('Canadá', 'CA', 'CAN', '124'),
('Caribe Neerlandés', 'BQ', 'BES', '535'),
('Catar', 'QA', 'QAT', '634'),
('Chad', 'TD', 'TCD', '148'),
('Chile', 'CL', 'CHL', '152'),
('China', 'CN', 'CHN', '156'),
('Chipre', 'CY', 'CYP', '196'),
('Colombia', 'CO', 'COL', '170'),
('Comoras', 'KM', 'COM', '174'),
('Corea del Norte', 'KP', 'PRK', '408'),
('Corea del Sur', 'KR', 'KOR', '410'),
('Costa de Marfil', 'CI', 'CIV', '384'),
('Costa Rica', 'CR', 'CRI', '188'),
('Croacia', 'HR', 'HRV', '191'),
('Cuba', 'CU', 'CUB', '192'),
('Curazao', 'CW', 'CUW', '531'),
('Dinamarca', 'DK', 'DNK', '208'),
('Dominica', 'DM', 'DMA', '212'),
('Ecuador', 'EC', 'ECU', '218'),
('Egipto', 'EG', 'EGY', '818'),
('El Salvador', 'SV', 'SLV', '222'),
('Emiratos árabes Unidos', 'AE', 'ARE', '784'),
('Eritrea', 'ER', 'ERI', '232'),
('Eslovaquia', 'SK', 'SVK', '703'),
('Eslovenia', 'SI', 'SVN', '705'),
('España', 'ES', 'ESP', '724'),
('Estados Federados de Micronesia', 'FM', 'FSM', '583'),
('Estados Unidos', 'US', 'USA', '840'),
('Estonia', 'EE', 'EST', '233'),
('Etiopía', 'ET', 'ETH', '231'),
('Filipinas', 'PH', 'PHL', '608'),
('Finlandia', 'FI', 'FIN', '246'),
('Fiyi', 'FJ', 'FJI', '242'),
('Francia', 'FR', 'FRA', '250'),
('Gabon', 'GA', 'GAB', '266'),
('Gambia', 'GM', 'GMB', '270'),
('Georgia', 'GE', 'GEO', '268'),
('Ghana', 'GH', 'GHA', '288'),
('Gibraltar', 'GI', 'GIB', '292'),
('Granada', 'GD', 'GRD', '308'),
('Grecia', 'GR', 'GRC', '300'),
('Groenlandia', 'GL', 'GRL', '304'),
('Guadelupe', 'GP', 'GLP', '312'),
('Guam', 'GU', 'GUM', '316'),
('Guatemala', 'GT', 'GTM', '320'),
('Guayana Francesa', 'GF', 'GUF', '254'),
('Guernsey', 'GG', 'GGY', '831'),
('Guinea', 'GN', 'GIN', '324'),
('Guinea Ecuatorial', 'GQ', 'GNQ', '226'),
('Guinea-Bissau', 'GW', 'GNB', '624'),
('Guyana', 'GY', 'GUY', '328'),
('Haití', 'HT', 'HTI', '332'),
('Honduras', 'HN', 'HND', '340'),
('Hong Kong', 'HK', 'HKG', '344'),
('Hungría', 'HU', 'HUN', '348'),
('Iceland', 'IS', 'ISL', '352'),
('India', 'IN', 'IND', '356'),
('Indonesia', 'ID', 'IDN', '360'),
('Irak', 'IQ', 'IRQ', '368'),
('Iran', 'IR', 'IRN', '364'),
('Isla de Man', 'IM', 'IMN', '833'),
('Isla de Navidad', 'CX', 'CXR', '162'),
('Isla Norfolk', 'NF', 'NFK', '574'),
('Islandia', 'IE', 'IRL', '372'),
('Islas Caimán', 'KY', 'CYM', '136'),
('Islas Cocos', 'CC', 'CCK', '166'),
('Islas Cook', 'CK', 'COK', '184'),
('Islas Feroe', 'FO', 'FRO', '234'),
('Islas Georgias y Sandwich del Sur', 'GS', 'SGS', '239'),
('Islas Malvinas', 'FK', 'FLK', '238'),
('Islas Marianas del Norte', 'MP', 'MNP', '580'),
('Islas Marshall', 'MH', 'MHL', '584'),
('Islas Pitcairn', 'PN', 'PCN', '612'),
('Islas Salomón', 'SB', 'SLB', '90'),
('Islas Turcas y Caicos', 'TC', 'TCA', '796'),
('Islas Vírgenes Británicas', 'VG', 'VGB', '92'),
('Islas Vírgenes de los Estados Unidos', 'VI', 'VIR', '850'),
('Israel', 'IL', 'ISR', '376'),
('Italia', 'IT', 'ITA', '380'),
('Jamaica', 'JM', 'JAM', '388'),
('Japón', 'JP', 'JPN', '392'),
('Jersey', 'JE', 'JEY', '832'),
('Jordania', 'JO', 'JOR', '400'),
('Kazajistán', 'KZ', 'KAZ', '398'),
('Kenia', 'KE', 'KEN', '404'),
('Kirguistán', 'KG', 'KGZ', '417'),
('Kiribati', 'KI', 'KIR', '296'),
('Kosovo', 'XK', 'XKX', '153'),
('Kuweit', 'KW', 'KWT', '414'),
('Laos', 'LA', 'LAO', '418'),
('Lesoto', 'LS', 'LSO', '426'),
('Letonia', 'LV', 'LVA', '428'),
('Libano', 'LB', 'LBN', '422'),
('Liberia', 'LR', 'LBR', '430'),
('Libia', 'LY', 'LBY', '434'),
('Liechtenstein', 'LI', 'LIE', '438'),
('Lituania', 'LT', 'LTU', '440'),
('Luxemburgo', 'LU', 'LUX', '442'),
('Macao', 'MO', 'MAC', '446'),
('Macedonia', 'MK', 'MKD', '807'),
('Madagascar', 'MG', 'MDG', '450'),
('Malasia', 'MY', 'MYS', '458'),
('Malaui', 'MW', 'MWI', '454'),
('Maldivas', 'MV', 'MDV', '462'),
('Mali', 'ML', 'MLI', '466'),
('Malta', 'MT', 'MLT', '470'),
('Marruecos', 'MA', 'MAR', '504'),
('Martinica', 'MQ', 'MTQ', '474'),
('Mauricio', 'MU', 'MUS', '480'),
('Mauritania', 'MR', 'MRT', '478'),
('Mayotte', 'YT', 'MYT', '175'),
('México', 'MX', 'MEX', '484'),
('Moldavia', 'MD', 'MDA', '498'),
('Monaco', 'MC', 'MCO', '492'),
('Mongolia', 'MN', 'MNG', '496'),
('Monténégro', 'ME', 'MNE', '499'),
('Montserrat', 'MS', 'MSR', '500'),
('Mozambique', 'MZ', 'MOZ', '508'),
('Namibia', 'NA', 'NAM', '516'),
('Nauru', 'NR', 'NRU', '520'),
('Nepal', 'NP', 'NPL', '524'),
('Nicaragua', 'NI', 'NIC', '558'),
('Niger', 'NE', 'NER', '562'),
('Nigeria', 'NG', 'NGA', '566'),
('Niue', 'NU', 'NIU', '570'),
('Noruega', 'NO', 'NOR', '578'),
('Nueva Caledonia', 'NC', 'NCL', '540'),
('Nueva Zelanda', 'NZ', 'NZL', '554'),
('Omán', 'OM', 'OMN', '512'),
('Países Bajos', 'NL', 'NLD', '528'),
('Pakistán', 'PK', 'PAK', '586'),
('Palaos', 'PW', 'PLW', '585'),
('Palestina', 'PS', 'PSE', '275'),
('Panama', 'PA', 'PAN', '591'),
('Papúa Nueva Guinea', 'PG', 'PNG', '598'),
('Paraguay', 'PY', 'PRY', '600'),
('Perú', 'PE', 'PER', '604'),
('Polinesia Francesa', 'PF', 'PYF', '258'),
('Polonia', 'PL', 'POL', '616'),
('Portugal', 'PT', 'PRT', '620'),
('Puerto Rico', 'PR', 'PRI', '630'),
('Reino Unido', 'GB', 'GBR', '826'),
('República árabe Saharaui DemocrÁtica', 'EH', 'ESH', '732'),
('República Centroafricana', 'CF', 'CAF', '140'),
('República Checa', 'CZ', 'CZE', '203'),
('República del Congo', 'CG', 'COG', '178'),
('República DemocrÁtica del Congo', 'CD', 'COD', '180'),
('República Dominicana', 'DO', 'DOM', '214'),
('Reunión', 'RE', 'REU', '638'),
('Ruanda', 'RW', 'RWA', '646'),
('Rumania', 'RO', 'ROU', '642'),
('Rusia', 'RU', 'RUS', '643'),
('Samoa', 'WS', 'WSM', '882'),
('Samoa Americana', 'AS', 'ASM', '16'),
('San Bartolomé', 'BL', 'BLM', '652'),
('San Cristóbal y Nieves', 'KN', 'KNA', '659'),
('San Marino', 'SM', 'SMR', '674'),
('San Martín', 'MF', 'MAF', '534'),
('San Pedro y Miquelón', 'PM', 'SPM', '666'),
('San Vicente y las Granadinas', 'VC', 'VCT', '670'),
('Santa Lucía', 'LC', 'LCA', '662'),
('Santo Tomé y Príncipe', 'ST', 'STP', '678'),
('Senegal', 'SN', 'SEN', '686'),
('Serbia', 'RS', 'SRB', '688'),
('Seychelles', 'SC', 'SYC', '690'),
('Sierra Leona', 'SL', 'SLE', '694'),
('Singapur', 'SG', 'SGP', '702'),
('Sint Helena, Ascension and Tristan da Cunha', 'SH', 'SHN', '654'),
('Sint-Maarten', 'SX', 'SXM', '663'),
('Siria', 'SY', 'SYR', '760'),
('Somalia', 'SO', 'SOM', '706'),
('Sri Lanka', 'LK', 'LKA', '144'),
('eSwatani', 'SZ', 'SWZ', '748'),
('Sudáfrica', 'ZA', 'ZAF', '710'),
('Sudán', 'SD', 'SDN', '729'),
('Sudán del Sur', 'SS', 'SSD', '728'),
('Suecia', 'SE', 'SWE', '752'),
('Suiza', 'CH', 'CHE', '756'),
('Surinam', 'SR', 'SUR', '740'),
('Tailandia', 'TH', 'THA', '764'),
('Taiwan', 'TW', 'TWN', '158'),
('Tanzania', 'TZ', 'TZA', '834'),
('Tayikistán', 'TJ', 'TJK', '762'),
('Territorio Británico del Océano índico', 'IO', 'IOT', '86'),
('Tierras Australes y Antárticas Francesas', 'TF', 'ATF', '260'),
('Timor Oriental', 'TL', 'TLS', '626'),
('Togo', 'TG', 'TGO', '768'),
('Tokelau', 'TK', 'TKL', '772'),
('Tonga', 'TO', 'TON', '776'),
('Trinidad y Tobago', 'TT', 'TTO', '780'),
('Túnez', 'TN', 'TUN', '788'),
('Turkmenistán', 'TM', 'TKM', '795'),
('Turquía', 'TR', 'TUR', '792'),
('Tuvalu', 'TV', 'TUV', '798'),
('Ucrania', 'UA', 'UKR', '804'),
('Uganda', 'UG', 'UGA', '800'),
('Uruguay', 'UY', 'URY', '858'),
('Uzbekistán', 'UZ', 'UZB', '860'),
('Vanuatu', 'VU', 'VUT', '548'),
('Vaticano', 'VA', 'VAT', '336'),
('Venezuela', 'VE', 'VEN', '862'),
('Vietnam', 'VN', 'VNM', '704'),
('Wallis y Futuna', 'WF', 'WLF', '876'),
('Yemen', 'YE', 'YEM', '887'),
('Yibuti', 'DJ', 'DJI', '262'),
('Zambia', 'ZM', 'ZMB', '894'),
('Zimbabwe', 'ZW', 'ZWE', '716');
--
INSERT INTO subdivisioncategories (description) 
VALUES ('departament'),('capital district'),('state'),('district'),('outlying area');

INSERT INTO citiesormunicipalities (name, statereg_id) VALUES
-- Amazonas (CO-AMA)
('1', 'LETICIA', 'CO-AMA'),
('2', 'EL ENCANTO', 'CO-AMA'),
('3', 'LA CHORRERA', 'CO-AMA'),
('4', 'LA PEDRERA', 'CO-AMA'),
('5', 'LA VICTORIA', 'CO-AMA'),
('6', 'MIRITI - PARANA', 'CO-AMA'),
('7', 'PUERTO ALEGRIA', 'CO-AMA'),
('8', 'PUERTO ARICA', 'CO-AMA'),
('9', 'PUERTO NARIÑO', 'CO-AMA'),

-- Antioquia (CO-ANT)
('10', 'MEDELLIN', 'CO-ANT'),
('11', 'ABEJORRAL', 'CO-ANT'),
('12', 'ABRIAQUI', 'CO-ANT'),
('13', 'ALEJANDRIA', 'CO-ANT'),
('14', 'AMAGA', 'CO-ANT'),
('15', 'AMALFI', 'CO-ANT'),
('16', 'ANDES', 'CO-ANT'),
('17', 'ANGELOPOLIS', 'CO-ANT'),
('18', 'ANGOSTURA', 'CO-ANT'),
('19', 'ANORI', 'CO-ANT'),
('20', 'SANTAFE DE ANTIOQUIA', 'CO-ANT'),
('21', 'ANZA', 'CO-ANT'),
('22', 'APARTADO', 'CO-ANT'),
('23', 'ARBOLETES', 'CO-ANT'),
('24', 'ARGELIA', 'CO-ANT'),

-- Atlántico (CO-ATL)
('25', 'BARRANQUILLA', 'CO-ATL'),
('26', 'BARANOA', 'CO-ATL'),
('27', 'CAMPO DE LA CRUZ', 'CO-ATL'),
('28', 'CANDELARIA', 'CO-ATL'),
('29', 'GALAPA', 'CO-ATL'),
('30', 'JUAN DE ACOSTA', 'CO-ATL'),
('31', 'LURUACO', 'CO-ATL'),
('32', 'MALAMBO', 'CO-ATL'),
('33', 'MANATI', 'CO-ATL'),
('34', 'PALMAR DE VARELA', 'CO-ATL'),
('35', 'PIOJO', 'CO-ATL'),
('36', 'POLONUEVO', 'CO-ATL'),
('37', 'PONEDERA', 'CO-ATL'),
('38', 'PUERTO COLOMBIA', 'CO-ATL'),
('39', 'REPELON', 'CO-ATL'),

-- Bolívar (CO-BOL)
('40', 'CARTAGENA', 'CO-BOL'),
('41', 'ACHI', 'CO-BOL'),
('42', 'ALTOS DEL ROSARIO', 'CO-BOL'),
('43', 'ARENAL', 'CO-BOL'),
('44', 'ARJONA', 'CO-BOL'),
('45', 'ARROYOHONDO', 'CO-BOL'),
('46', 'BARRANCO DE LOBA', 'CO-BOL'),
('47', 'CALAMAR', 'CO-BOL'),
('48', 'CANTAGALLO', 'CO-BOL'),
('49', 'CICUCO', 'CO-BOL'),
('50', 'CORDOBA', 'CO-BOL'),
('51', 'CLEMENCIA', 'CO-BOL'),
('52', 'EL CARMEN DE BOLIVAR', 'CO-BOL'),
('53', 'EL GUAMO', 'CO-BOL'),
('54', 'EL PEÑON', 'CO-BOL'),

-- Boyacá (CO-BOY)
('55', 'TUNJA', 'CO-BOY'),
('56', 'ALMEIDA', 'CO-BOY'),
('57', 'AQUITANIA', 'CO-BOY'),
('58', 'ARCABUCO', 'CO-BOY'),
('59', 'BELEN', 'CO-BOY'),
('60', 'BERBEO', 'CO-BOY'),
('61', 'BETEITIVA', 'CO-BOY'),
('62', 'BOAVITA', 'CO-BOY'),
('63', 'BOYACA', 'CO-BOY'),
('64', 'BRICEÑO', 'CO-BOY'),
('65', 'BUENAVISTA', 'CO-BOY'),
('66', 'BUSBANZA', 'CO-BOY'),
('67', 'CALDAS', 'CO-BOY'),
('68', 'CAMPOHERMOSO', 'CO-BOY'),
('69', 'CERINZA', 'CO-BOY'),

-- Caldas (CO-CAL)
('70', 'MANIZALES', 'CO-CAL'),
('71', 'AGUADAS', 'CO-CAL'),
('72', 'ANSERMA', 'CO-CAL'),
('73', 'ARANZAZU', 'CO-CAL'),
('74', 'BELALCAZAR', 'CO-CAL'),
('75', 'CHINCHINA', 'CO-CAL'),
('76', 'FILADELFIA', 'CO-CAL'),
('77', 'LA DORADA', 'CO-CAL'),
('78', 'LA MERCED', 'CO-CAL'),
('79', 'MANZANARES', 'CO-CAL'),
('80', 'MARMATO', 'CO-CAL'),
('81', 'MARQUETALIA', 'CO-CAL'),
('82', 'MARULANDA', 'CO-CAL'),
('83', 'NEIRA', 'CO-CAL'),
('84', 'NORCASIA', 'CO-CAL'),

-- Caquetá (CO-CAQ)
('85', 'FLORENCIA', 'CO-CAQ'),
('86', 'ALBANIA', 'CO-CAQ'),
('87', 'BELEN DE LOS ANDAQUIES', 'CO-CAQ'),
('88', 'CARTAGENA DEL CHAIRA', 'CO-CAQ'),
('89', 'CURILLO', 'CO-CAQ'),
('90', 'EL DONCELLO', 'CO-CAQ'),
('91', 'EL PAUJIL', 'CO-CAQ'),
('92', 'LA MONTAÑITA', 'CO-CAQ'),
('93', 'MILAN', 'CO-CAQ'),
('94', 'MORELIA', 'CO-CAQ'),
('95', 'PUERTO RICO', 'CO-CAQ'),
('96', 'SAN JOSE DE LA FRAGUA', 'CO-CAQ'),
('97', 'SAN VICENTE DEL CAGUAN', 'CO-CAQ'),
('98', 'SOLANO', 'CO-CAQ'),
('99', 'SOLITA', 'CO-CAQ'),

-- Casanare (CO-CAS)
('100', 'YOPAL', 'CO-CAS'),
('101', 'AGUAZUL', 'CO-CAS'),
('102', 'CHAMEZA', 'CO-CAS'),
('103', 'HATO COROZAL', 'CO-CAS'),
('104', 'LA SALINA', 'CO-CAS'),
('105', 'MANI', 'CO-CAS'),
('106', 'MONTERREY', 'CO-CAS'),
('107', 'NUNCHIA', 'CO-CAS'),
('108', 'OROCUE', 'CO-CAS'),
('109', 'PAZ DE ARIPORO', 'CO-CAS'),
('110', 'PORE', 'CO-CAS'),
('111', 'RECETOR', 'CO-CAS'),
('112', 'SABANALARGA', 'CO-CAS'),
('113', 'SACAMA', 'CO-CAS'),
('114', 'SAN LUIS DE PALENQUE', 'CO-CAS'),

-- Cauca (CO-CAU)
('115', 'POPAYAN', 'CO-CAU'),
('116', 'ALMAGUER', 'CO-CAU'),
('117', 'ARGELIA', 'CO-CAU'),
('118', 'BALBOA', 'CO-CAU'),
('119', 'BOLIVAR', 'CO-CAU'),
('120', 'BUENOS AIRES', 'CO-CAU'),
('121', 'CAJIBIO', 'CO-CAU'),
('122', 'CALDONO', 'CO-CAU'),
('123', 'CALOTO', 'CO-CAU'),
('124', 'CORINTO', 'CO-CAU'),
('125', 'EL TAMBO', 'CO-CAU'),
('126', 'FLORENCIA', 'CO-CAU'),
('127', 'GUAPI', 'CO-CAU'),
('128', 'INZA', 'CO-CAU'),
('129', 'JAMBALO', 'CO-CAU'),

-- Cesar (CO-CES)
('130', 'VALLEDUPAR', 'CO-CES'),
('131', 'AGUACHICA', 'CO-CES'),
('132', 'AGUSTIN CODAZZI', 'CO-CES'),
('133', 'ASTREA', 'CO-CES'),
('134', 'BECERRIL', 'CO-CES'),
('135', 'BOSCONIA', 'CO-CES'),
('136', 'CHIMICHAGUA', 'CO-CES'),
('137', 'CHIRIGUANA', 'CO-CES'),
('138', 'CURUMANI', 'CO-CES'),
('139', 'EL COPEY', 'CO-CES'),
('140', 'EL PASO', 'CO-CES'),
('141', 'GAMARRA', 'CO-CES'),
('142', 'GONZALEZ', 'CO-CES'),
('143', 'LA GLORIA', 'CO-CES'),
('144', 'LA JAGUA DE IBIRICO', 'CO-CES'),

-- Chocó (CO-CHO)
('145', 'QUIBDO', 'CO-CHO'),
('146', 'ACANDI', 'CO-CHO'),
('147', 'ALTO BAUDO', 'CO-CHO'),
('148', 'ATRATO', 'CO-CHO'),
('149', 'BAGADO', 'CO-CHO'),
('150', 'BAHIA SOLANO', 'CO-CHO'),
('151', 'BAJO BAUDO', 'CO-CHO'),
('152', 'BELEN DE BAJIRA', 'CO-CHO'),
('153', 'BOJAYA', 'CO-CHO'),
('154', 'EL CANTON DEL SAN PABLO', 'CO-CHO'),
('155', 'CARMEN DEL DARIEN', 'CO-CHO'),
('156', 'CERTEGUI', 'CO-CHO'),
('157', 'CONDOTO', 'CO-CHO'),
('158', 'EL CARMEN DE ATRATO', 'CO-CHO'),
('159', 'EL LITORAL DEL SAN JUAN', 'CO-CHO'),

-- Cundinamarca (CO-CUN)
('160', 'AGUA DE DIOS', 'CO-CUN'),
('161', 'ALBAN', 'CO-CUN'),
('162', 'ANAPOIMA', 'CO-CUN'),
('163', 'ANOLAIMA', 'CO-CUN'),
('164', 'ARBELAEZ', 'CO-CUN'),
('165', 'BELTRAN', 'CO-CUN'),
('166', 'BITUIMA', 'CO-CUN'),
('167', 'BOJACA', 'CO-CUN'),
('168', 'CABRERA', 'CO-CUN'),
('169', 'CACHIPAY', 'CO-CUN'),
('170', 'CAJICA', 'CO-CUN'),
('171', 'CAPARRAPI', 'CO-CUN'),
('172', 'CAQUEZA', 'CO-CUN'),
('173', 'CARMEN DE CARUPA', 'CO-CUN'),
('174', 'CHAGUANI', 'CO-CUN'),

-- Córdoba (CO-COR)
('175', 'MONTERIA', 'CO-COR'),
('176', 'AYAPEL', 'CO-COR'),
('177', 'BUENAVISTA', 'CO-COR'),
('178', 'CANALETE', 'CO-COR'),
('179', 'CERETE', 'CO-COR'),
('180', 'CHIMA', 'CO-COR'),
('181', 'CHINU', 'CO-COR'),
('182', 'CIENAGA DE ORO', 'CO-COR'),
('183', 'COTORRA', 'CO-COR'),
('184', 'LA APARTADA', 'CO-COR'),
('185', 'LORICA', 'CO-COR'),
('186', 'LOS CORDOBAS', 'CO-COR'),
('187', 'MOMIL', 'CO-COR'),
('188', 'MONTELIBANO', 'CO-COR'),
('189', 'MOÑITOS', 'CO-COR'),

-- Bogotá D.C. (CO-DC)
('190', 'BOGOTA', 'CO-DC'),

-- Guainía (CO-GUA)
('191', 'INIRIDA', 'CO-GUA'),
('192', 'BARRANCO MINAS', 'CO-GUA'),
('193', 'MAPIRIPANA', 'CO-GUA'),
('194', 'SAN FELIPE', 'CO-GUA'),
('195', 'PUERTO COLOMBIA', 'CO-GUA'),
('196', 'LA GUADALUPE', 'CO-GUA'),
('197', 'CACAHUAL', 'CO-GUA'),
('198', 'PANA PANA', 'CO-GUA'),
('199', 'MORICHAL', 'CO-GUA'),

-- Guaviare (CO-GUV)
('200', 'SAN JOSE DEL GUAVIARE', 'CO-GUV'),
('201', 'CALAMAR', 'CO-GUV'),
('202', 'EL RETORNO', 'CO-GUV'),
('203', 'MIRAFLORES', 'CO-GUV'),

-- Huila (CO-HUI)
('204', 'NEIVA', 'CO-HUI'),
('205', 'ACEVEDO', 'CO-HUI'),
('206', 'AGRADO', 'CO-HUI'),
('207', 'AIPE', 'CO-HUI'),
('208', 'ALGECIRAS', 'CO-HUI'),
('209', 'ALTAMIRA', 'CO-HUI'),
('210', 'BARAYA', 'CO-HUI'),
('211', 'CAMPOALEGRE', 'CO-HUI'),
('212', 'COLOMBIA', 'CO-HUI'),
('213', 'ELIAS', 'CO-HUI'),
('214', 'GARZON', 'CO-HUI'),
('215', 'GIGANTE', 'CO-HUI'),
('216', 'GUADALUPE', 'CO-HUI'),
('217', 'HOBO', 'CO-HUI'),
('218', 'IQUIRA', 'CO-HUI'),

-- La Guajira (CO-LAG)
('219', 'RIOHACHA', 'CO-LAG'),
('220', 'ALBANIA', 'CO-LAG'),
('221', 'BARRANCAS', 'CO-LAG'),
('222', 'DIBULLA', 'CO-LAG'),
('223', 'DISTRACCION', 'CO-LAG'),
('224', 'EL MOLINO', 'CO-LAG'),
('225', 'FONSECA', 'CO-LAG'),
('226', 'HATONUEVO', 'CO-LAG'),
('227', 'LA JAGUA DEL PILAR', 'CO-LAG'),
('228', 'MAICAO', 'CO-LAG'),
('229', 'MANAURE', 'CO-LAG'),
('230', 'SAN JUAN DEL CESAR', 'CO-LAG'),
('231', 'URIBIA', 'CO-LAG'),
('232', 'URUMITA', 'CO-LAG'),
('233', 'VILLANUEVA', 'CO-LAG'),

-- Magdalena (CO-MAG)
('234', 'SANTA MARTA', 'CO-MAG'),
('235', 'ALGARROBO', 'CO-MAG'),
('236', 'ARACATACA', 'CO-MAG'),
('237', 'ARIGUANI', 'CO-MAG'),
('238', 'CERRO SAN ANTONIO', 'CO-MAG'),
('239', 'CHIVOLO', 'CO-MAG'),
('240', 'CIENAGA', 'CO-MAG'),
('241', 'CONCORDIA', 'CO-MAG'),
('242', 'EL BANCO', 'CO-MAG'),
('243', 'EL PIÑON', 'CO-MAG'),
('244', 'EL RETEN', 'CO-MAG'),
('245', 'FUNDACION', 'CO-MAG'),
('246', 'GUAMAL', 'CO-MAG'),
('247', 'NUEVA GRANADA', 'CO-MAG'),
('248', 'PEDRAZA', 'CO-MAG'),

-- Meta (CO-MET)
('249', 'VILLAVICENCIO', 'CO-MET'),
('250', 'ACACIAS', 'CO-MET'),
('251', 'BARRANCA DE UPIA', 'CO-MET'),
('252', 'CABUYARO', 'CO-MET'),
('253', 'CASTILLA LA NUEVA', 'CO-MET'),
('254', 'CUBARRAL', 'CO-MET'),
('255', 'CUMARAL', 'CO-MET'),
('256', 'EL CALVARIO', 'CO-MET'),
('257', 'EL CASTILLO', 'CO-MET'),
('258', 'EL DORADO', 'CO-MET'),
('259', 'FUENTE DE ORO', 'CO-MET'),
('260', 'GRANADA', 'CO-MET'),
('261', 'GUAMAL', 'CO-MET'),
('262', 'MAPIRIPAN', 'CO-MET'),
('263', 'MESETAS', 'CO-MET'),

-- Nariño (CO-NAR)
('264', 'PASTO', 'CO-NAR'),
('265', 'ALBAN', 'CO-NAR'),
('266', 'ALDANA', 'CO-NAR'),
('267', 'ANCUYA', 'CO-NAR'),
('268', 'ARBOLEDA', 'CO-NAR'),
('269', 'BARBACOAS', 'CO-NAR'),
('270', 'BELEN', 'CO-NAR'),
('271', 'BUESACO', 'CO-NAR'),
('272', 'COLON', 'CO-NAR'),
('273', 'CONSACA', 'CO-NAR'),
('274', 'CONTADERO', 'CO-NAR'),
('275', 'CORDOBA', 'CO-NAR'),
('276', 'CUASPUD', 'CO-NAR'),
('277', 'CUMBAL', 'CO-NAR'),
('278', 'CUMBITARA', 'CO-NAR'),

-- Norte de Santander (CO-NSA)
('279', 'CUCUTA', 'CO-NSA'),
('280', 'ABREGO', 'CO-NSA'),
('281', 'ARBOLEDAS', 'CO-NSA'),
('282', 'BOCHALEMA', 'CO-NSA'),
('283', 'BUCARASICA', 'CO-NSA'),
('284', 'CACOTA', 'CO-NSA'),
('285', 'CACHIRA', 'CO-NSA'),
('286', 'CHINACOTA', 'CO-NSA'),
('287', 'CHITAGA', 'CO-NSA'),
('288', 'CONVENCION', 'CO-NSA'),
('289', 'CUCUTILLA', 'CO-NSA'),
('290', 'DURANIA', 'CO-NSA'),
('291', 'EL CARMEN', 'CO-NSA'),
('292', 'EL TARRA', 'CO-NSA'),
('293', 'EL ZULIA', 'CO-NSA'),

-- Putumayo (CO-PUT)
('294', 'MOCOA', 'CO-PUT'),
('295', 'COLON', 'CO-PUT'),
('296', 'ORITO', 'CO-PUT'),
('297', 'PUERTO ASIS', 'CO-PUT'),
('298', 'PUERTO CAICEDO', 'CO-PUT'),
('299', 'PUERTO GUZMAN', 'CO-PUT'),
('300', 'LEGUIZAMO', 'CO-PUT'),
('301', 'SIBUNDOY', 'CO-PUT'),
('302', 'SAN FRANCISCO', 'CO-PUT'),
('303', 'SAN MIGUEL', 'CO-PUT'),
('304', 'SANTIAGO', 'CO-PUT'),
('305', 'VALLE DEL GUAMUEZ', 'CO-PUT'),
('306', 'VILLAGARZON', 'CO-PUT'),

-- Quindío (CO-QUI)
('307', 'ARMENIA', 'CO-QUI'),
('308', 'BUENAVISTA', 'CO-QUI'),
('309', 'CALARCA', 'CO-QUI'),
('310', 'CIRCASIA', 'CO-QUI'),
('311', 'CORDOBA', 'CO-QUI'),
('312', 'FILANDIA', 'CO-QUI'),
('313', 'GENOVA', 'CO-QUI'),
('314', 'LA TEBAIDA', 'CO-QUI'),
('315', 'MONTENEGRO', 'CO-QUI'),
('316', 'PIJAO', 'CO-QUI'),
('317', 'QUIMBAYA', 'CO-QUI'),
('318', 'SALENTO', 'CO-QUI'),

-- Risaralda (CO-RIS)
('319', 'PEREIRA', 'CO-RIS'),
('320', 'APIA', 'CO-RIS'),
('321', 'BALBOA', 'CO-RIS'),
('322', 'BELEN DE UMBRIA', 'CO-RIS'),
('323', 'DOSQUEBRADAS', 'CO-RIS'),
('324', 'GUATICA', 'CO-RIS'),
('325', 'LA CELIA', 'CO-RIS'),
('326', 'LA VIRGINIA', 'CO-RIS'),
('327', 'MARSELLA', 'CO-RIS'),
('328', 'MISTRATO', 'CO-RIS'),
('329', 'PUEBLO RICO', 'CO-RIS'),
('330', 'QUINCHIA', 'CO-RIS'),
('331', 'SANTA ROSA DE CABAL', 'CO-RIS'),
('332', 'SANTUARIO', 'CO-RIS'),

-- San Andrés (CO-SAP)
('333', 'SAN ANDRES', 'CO-SAP'),
('334', 'PROVIDENCIA', 'CO-SAP'),

-- Santander (CO-SAN)
('335', 'BUCARAMANGA', 'CO-SAN'),
('336', 'AGUADA', 'CO-SAN'),
('337', 'ALBANIA', 'CO-SAN'),
('338', 'ARATOCA', 'CO-SAN'),
('339', 'BARBOSA', 'CO-SAN'),
('340', 'BARICHARA', 'CO-SAN'),
('341', 'BARRANCABERMEJA', 'CO-SAN'),
('342', 'BETULIA', 'CO-SAN'),
('343', 'BOLIVAR', 'CO-SAN'),
('344', 'CABRERA', 'CO-SAN'),
('345', 'CALIFORNIA', 'CO-SAN'),
('346', 'CAPITANEJO', 'CO-SAN'),
('347', 'CARCASI', 'CO-SAN'),
('348', 'CEPITA', 'CO-SAN'),
('349', 'CERRITO', 'CO-SAN'),

-- Sucre (CO-SUC)
('350', 'SINCELEJO', 'CO-SUC'),
('351', 'BUENAVISTA', 'CO-SUC'),
('352', 'CAIMITO', 'CO-SUC'),
('353', 'COLOSO', 'CO-SUC'),
('354', 'COROZAL', 'CO-SUC'),
('355', 'CHALAN', 'CO-SUC'),
('356', 'EL ROBLE', 'CO-SUC'),
('357', 'GALERAS', 'CO-SUC'),
('358', 'GUARANDA', 'CO-SUC'),
('359', 'LA UNION', 'CO-SUC'),
('360', 'LOS PALMITOS', 'CO-SUC'),
('361', 'MAJAGUAL', 'CO-SUC'),
('362', 'MORROA', 'CO-SUC'),
('363', 'OVEJAS', 'CO-SUC'),
('364', 'PALMITO', 'CO-SUC'),

-- Tolima (CO-TOL)
('365', 'IBAGUE', 'CO-TOL'),
('366', 'ALPUJARRA', 'CO-TOL'),
('367', 'ALVARADO', 'CO-TOL'),
('368', 'AMBALEMA', 'CO-TOL'),
('369', 'ANZOATEGUI', 'CO-TOL'),
('370', 'ARMERO', 'CO-TOL'),
('371', 'ATACO', 'CO-TOL'),
('372', 'CAJAMARCA', 'CO-TOL'),
('373', 'CARMEN DE APICALA', 'CO-TOL'),
('374', 'CASABIANCA', 'CO-TOL'),
('375', 'CHAPARRAL', 'CO-TOL'),
('376', 'COELLO', 'CO-TOL'),
('377', 'COYAIMA', 'CO-TOL'),
('378', 'CUNDAY', 'CO-TOL'),
('379', 'DOLORES', 'CO-TOL'),

-- Valle del Cauca (CO-VAC)
('380', 'CALI', 'CO-VAC'),
('381', 'ALCALA', 'CO-VAC'),
('382', 'ANDALUCIA', 'CO-VAC'),
('383', 'ANSERMANUEVO', 'CO-VAC'),
('384', 'ARGELIA', 'CO-VAC'),
('385', 'BOLIVAR', 'CO-VAC'),
('386', 'BUENAVENTURA', 'CO-VAC'),
('387', 'GUADALAJARA DE BUGA', 'CO-VAC'),
('388', 'BUGALAGRANDE', 'CO-VAC'),
('389', 'CAICEDONIA', 'CO-VAC'),
('390', 'CALIMA', 'CO-VAC'),
('391', 'CANDELARIA', 'CO-VAC'),
('392', 'CARTAGO', 'CO-VAC'),
('393', 'DAGUA', 'CO-VAC'),
('394', 'EL AGUILA', 'CO-VAC'),

-- Vaupés (CO-VAU)
('395', 'MITU', 'CO-VAU'),
('396', 'CARURU', 'CO-VAU'),
('397', 'PACOA', 'CO-VAU'),
('398', 'TARAIRA', 'CO-VAU'),
('399', 'PAPUNAUA', 'CO-VAU'),
('400', 'YAVARATE', 'CO-VAU'),

-- Vichada (CO-VID)
('401', 'PUERTO CARREÑO', 'CO-VID'),
('402', 'LA PRIMAVERA', 'CO-VID'),
('403', 'SANTA ROSALIA', 'CO-VID'),
('404', 'CUMARIBO', 'CO-VID');